plantsproj/config/routes.rb
Coudsigdeviseapp::Application.routes.draw do

  resources :plants

  get "users/index"

  get "users/show"

  devise_for :users
  
  resources :users, :only => [:index, :show] do
   resources :plants, :shallow => true
 end

  root :to => "home#index"

end

plantsproj/app/models/plant.rb
class Plant < ActiveRecord::Base
  belongs_to :user

# validation
  validates_presence_of :commonname
end

plantsproj/app/models/user.rb
class User < ActiveRecord::Base
  
 has_many :plants, :dependent => :destroy
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

validates_presence_of :name
validates_uniqueness_of :email, :case_sensitive => false

has_friendly_id :name, :use_slug => true, :strip_non_ascii => true
end

plantsproj/app/controllers/copy_plants_controller.rb
class PlantsController < ApplicationController
  
#  making sure users are logged in
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_user, :except => [:index, :show]
  
  
  respond_to :html
  
  
  
  # GET /plants
  # GET /plants.xml
  def index
    @plants = Plant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @plants }
    end
  end

  # GET /plants/1
  # GET /plants/1.xml
  def show
    @plant = Plant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @plant }
    end
  end

  # GET /plants/new
  # GET /plants/new.xml
  def new
    @plant = Plant.new(:user => @user)

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @plant }
    end
  end

  # GET /plants/1/edit
  def edit
    @plant = Plant.find(params[:id])
  end

  # POST /plants
  # POST /plants.xml
  def create
    @plant = Plant.new(params[:plant])

    respond_to do |format|
      if @plant.save
        format.html { redirect_to(@plant, :notice => 'Plant was successfully created.') }
        format.xml  { render :xml => @plant, :status => :created, :location => @plant }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @plant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /plants/1
  # PUT /plants/1.xml
  def update
    @plant = Plant.find(params[:id])

    respond_to do |format|
      if @plant.update_attributes(params[:plant])
        format.html { redirect_to(@plant, :notice => 'Plant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @plant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.xml
  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    respond_to do |format|
      format.html { redirect_to(@user) }
      format.xml  { head :ok }
    end  
  end
  
  protected

    def find_user
      if params[:user_id]
        @user = User.find(params[:user_id])
      else
        @plant = Plant.find(params[:id])
        @user = @plant.user
      end
      unless current_user == @user
        redirect_to @user, :alert => "Are you logged in properly?"
      end
    end
  
  
end

plantsproj/app/controllers/plants_controller.rb
class PlantsController < ApplicationController

  
#  making sure users are logged in
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_user, :except => [:index, :show]
  
  
  respond_to :html

  # GET /plants
  # GET /plants.xml
  def index
    @plants = Plant.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @plants }
    end
  end

  # GET /plants/1
  # GET /plants/1.xml
  def show
    @plant = Plant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @plant }
    end
  end

  # GET /plants/new
  # GET /plants/new.xml
  def new
    @plant = Plant.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @plant }
    end
  end

  # GET /plants/1/edit
  def edit
    @plant = Plant.find(params[:id])
  end

  # POST /plants
  # POST /plants.xml
  def create
    @plant = Plant.new(params[:plant])

    respond_to do |format|
      if @plant.save
        format.html { redirect_to(@plant, :notice => 'Plant was successfully created.') }
        format.xml  { render :xml => @plant, :status => :created, :location => @plant }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @plant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /plants/1
  # PUT /plants/1.xml
  def update
    @plant = Plant.find(params[:id])

    respond_to do |format|
      if @plant.update_attributes(params[:plant])
        format.html { redirect_to(@plant, :notice => 'Plant was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @plant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.xml
  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    respond_to do |format|
      format.html { redirect_to(plants_url) }
      format.xml  { head :ok }
    end
  end

  protected

    def find_user
      if params[:user_id]
        @user = User.find(params[:user_id])
      else
        @plant = Plant.find(params[:id])
        @user = @plant.user
      end
      unless current_user == @user
        redirect_to @user, :alert => "Are you logged in properly?"
      end
    end

end

plantsproj/app/helpers/plant_helper.rb
module PlantHelper
end

plantsproj/app/views/home/index.html.erb
<h1>Welcome to Your Plant Database</h1>

<p>Description of the site</p>

plantsproj/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plants</title>
 <%= stylesheet_link_tag "styles" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
 <div id="maincontent">
           
<div id="navigation">
  <ul>
    <%= render 'devise/menu/registration_items' %>
    <%= render 'devise/menu/login_items' %>
  </ul>
</div>
  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p>
 
  <header id="topsection">Template Content for the whole site</header>
  <section id="main_content"> <%= yield %></section>
  <aside><p>right sidebar</p></aside>
  <footer class="clear"><p>copyright</p></footer>
  </div>

  
  
</body>
</html>

plantsproj/app/views/plants/_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commonname %><br />
    <%= f.text_field :commonname %>
  </div>
  <div class="field">
    <%= f.label :latinname %><br />
    <%= f.text_field :latinname %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :bloomstart %><br />
    <%= f.text_field :bloomstart %>
  </div>
  <div class="field">
    <%= f.label :bloomend %><br />
    <%= f.text_field :bloomend %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>

 <%= f.hidden_field(:user_id, :value => @plant.user_id) %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

plantsproj/app/views/plants/index.html.erb
<h1>Listing plants</h1>

<table>
  <tr>
    <th>Commonname</th>
    <th>Latinname</th>
    <th>Type</th>
    <th>Bloomstart</th>
    <th>Bloomend</th>
    <th>Active</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @plants.each do |plant| %>
  <tr>
    <td><%= plant.commonname %></td>
    <td><%= plant.latinname %></td>
    <td><%= plant.type %></td>
    <td><%= plant.bloomstart %></td>
    <td><%= plant.bloomend %></td>
    <td><%= plant.active %></td>
    <td><%= plant.user %></td>
    <td><%= link_to 'Show', plant %></td>
    <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
    <td><%= link_to 'Destroy', plant, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Plant', new_plant_path %>

plantsproj/app/views/plants/new.html.erb
<h1>New plant</h1>

<%= render 'form' %>

<%= link_to 'Back', plants_path %>

<%#= link_to @plant.user.name, user_path(@plant.user) %>

plantsproj/app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Commonname:</b>
  <%= @plant.commonname %>
</p>

<p>
  <b>Latinname:</b>
  <%= @plant.latinname %>
</p>

<p>
  <b>Type:</b>
  <%= @plant.type %>
</p>

<p>
  <b>Bloomstart:</b>
  <%= @plant.bloomstart %>
</p>

<p>
  <b>Bloomend:</b>
  <%= @plant.bloomend %>
</p>

<p>
  <b>Active:</b>
  <%= @plant.active %>
</p>

<p>
  <b>User:</b>
  <%= @plant.user %>
</p>


<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plant_path %>

plantsproj/app/views/users/show.html.erb
<h1>Welcome <%= @user.name %></h1>
<p><%= @user.email %></p>
<br />

<h3><%= @user.name %>'s Plants</h3>
<table>
<% @user.plants.each do |plant| %>
  <tr>
    <td><%= link_to plant.commonname, plant %></td>
    <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
    <td><%= link_to 'Destroy', plant, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to "Add New Plant", new_user_plant_path(@user) %>